structure:
    name: DanceRevolution
    #ChoreoGrapher Configs
    max_seq_len: 4500
    d_frame_vec: 438
    frame_emb_size: 200
    n_layers: 2
    n_head: 8
    d_k: 64
    d_v: 64
    d_model: 200
    d_inner: 1024
    dropout: 0.1
    d_pose_vec: 72
    pose_emb_size: 72
    condition_step: 10
    sliding_windown_size: 100
    lambda_v: 0.01
    cuda: True
    rotmat: False

loss_weight:
    mse_weight: 1
optimizer:
    type: Adam
    kwargs:
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0.0000
    schedular_kwargs:
        milestones: [2, 3]
        gamma: 0.1

train_data:
    name: aist   
    data_dir: data/aistpp_train_wav
    mode: train
    rotmat: False
    seq_len: 240
    move: 1

data:
    name: aist   
    train_dir: data/aistpp_train_wav
    test_dir: data/aistpp_test_full_wav

    seq_len: 240
    data_type: None
rotmat: True

test_data:
    name: aist 
    mode: test  
    data_dir: data/aistpp_test_full_wav
    move: 1
    rotmat: False

testing:
    height: 540
    width: 960
    ckpt_epoch: 24
    rotmat: True

expname: dance_revolution
epoch: 10
batch_size: 32
save_per_epochs: 1
test_freq: 1
log_per_updates: 1
seed: 42
rotmat: False
smpl_dir: /mnt/lustre/syli/dance/Bailando/smpl
cuda: True

