structure:
    name: FACT
    #ChoreoGrapher Configs
    n_embd: 800
    n_head: 10
    n_music: 438
    n_motion: 72
    n_output: 72
    block_size: 240
    music:
        n_embd: 800
        n_head: 10
        n_layer: 2
    motion:
        n_embd: 800
        n_head: 10
        n_layer: 2 
    cross_model:
        n_embd: 800
        n_head: 10
        n_layer: 12

    
loss_weight:
    mse_weight: 1
optimizer:
    type: Adam
    kwargs:
        lr: 0.0001
        betas: [0.9, 0.999]
        weight_decay: 0.0000
    schedular_kwargs:
        milestones: [10, 15]
        gamma: 0.1

train_data:
    name: aist   
    data_dir: /mnt/lustre/syli/dance/Bailando/data/aistpp_train_wav
    mode: train
    rotmat: False
    seq_len: 240
    move: 1


test_data:
    name: aist 
    mode: test  
    data_dir: /mnt/lustre/syli/dance/Bailando/data/aistpp_test_full_wav 
    move: 1
    rotmat: False

testing:
    height: 540
    width: 960
    ckpt_epoch: 24
    rotmat: True

expname: fact_full_shift12_1e-4_bsz32_beta0.9_wav
epoch: 500
batch_size: 32
save_per_epochs: 1
test_freq: 1
log_per_updates: 1
seed: 42
rotmat: False
cuda: True

