train_data:
    name: aist   
    data_dir: /mnt/lustre/syli/dance/Bailando/data/aistpp_train_wav
    mode: train
    rotmat: False
    seq_len: 240
    move: 40

test_data:
    name: aist 
    mode: test  
    data_dir: /mnt/lustre/syli/dance/Bailando/data/aistpp_test_full_wav 
    move: 8
    rotmat: False


