# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches:
     - main
    paths-ignore:
      - 'README.md'
      - 'README_CN.md'
      - 'docs/**'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README_CN.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Env
        run: |
          pip install coverage pytest
          pip install torch==1.7.1
          # pip install lpips trimesh smplx -i https://pypi.tuna.tsinghua.edu.cn/simple
          # pip install torch numpy mmcv -i https://pypi.tuna.tsinghua.edu.cn/simple
          # pip install opencv-python>=3 yapf imageio scikit-image -i https://pypi.tuna.tsinghua.edu.cn/simple

          # coverage run --source xrmogen/models -m pytest -s test/models
          # coverage xml
          # coverage report -m
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
